### ISSUE TITLE
Investment Cost factor in the cost function isn't correct

### ISSUE THREAD

**Issue by AlOussama** [Taiseer46055/MyPowerModels#11]
The Implementation of the investment cost needs to be updated:
https://github.com/Taiseer46055/MyPowerModels/blob/5c445cc4fac13ef4fa4be25267208dde03254fa1/src/core/objective.jl#L105

It should consider the installed capacity, because the investment cost factor is in €/MW. It should look like:

> sum((var(pm, n, :nE)[i] - ref(pm, n, :gen, i)["n0"]) * ref(pm, n, :gen, i)["investment"] * ref(pm, n, :gen, i)["pmax"]

**Comment by BnJahn** [comment]
No adjustment needed since the data has been corrected to be in €/generation unit
